# Build and deploy ViteJs app to GitHub Pages on push to main branch (or pull request to main branch)

name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: 'WEB/package-lock.json'
      - name: Install dependencies
        run: |
          npm ci
        working-directory: ./WEB
      - name: Build
        run: |
          npm run build
        working-directory: ./WEB
      - name: copy dist/index.html to dist/404.html
        run: |
          cp dist/index.html dist/404.html
        working-directory: ./WEB
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./WEB/dist
          publish_branch: gh-pages
