name: Build and Deploy to GH-Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: 'WEB/package-lock.json'

      - name: Build Frontend
        run: |
          npm ci
          npm run build
        working-directory: ./WEB

      - name: copy /WEB/dist/index.html to /WEB/build/404.html
        run: |
          cp ./dist/index.html ./dist/404.html
        working-directory: ./WEB

      - name: Deploy to GH-Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./WEB/build
