name: CI/CD Pipeline - Runs All Unit tests and if all pass, deploys the frontend to the gh-pages branch

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: 'BACKEND/package-lock.json'
      - name: Execute Backend Unit tests
        run: |
          npm ci
          npm run test
        working-directory: ./BACKEND

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: 'WEB/package-lock.json'
      - name: Execute Frontend Unit tests
        run: |
          npm ci
          npm run test
        working-directory: ./WEB
